/*
** EPITECH PROJECT, 2022
** B-YEP-400-LIL-4-1-indiestudio-clement.chausson
** File description:
** ClickableActionType
*/

#ifndef CLICKABLEACTIONTYPE_HPP_
#define CLICKABLEACTIONTYPE_HPP_

enum ClickableActionType {
    CLICKABLE_ACTION_NONE,
    CLICKABLE_ACTION_CHANGE_ECS,
    CLICKABLE_ACTION_OPEN_OPTIONS,
    CLICKABLE_ACTION_QUIT_GAME,
    CLICKABLE_ACTION_TEST,
    CLICKABLE_ACTION_CHOOSE_CHARACTER,
    CLICKABLE_ACTION_CHOOSE_SPANE,
    CLICKABLE_ACTION_CHOOSE_TRELAWNEY,
    CLICKABLE_ACTION_CHOOSE_SPROUT,
    CLICKABLE_ACTION_CHOOSE_MCG
};

#endif /* !CLICKABLEACTIONTYPE_HPP_ */
